name: backfeed
description: "Backfeed is a relationship feedback app designed to enhance key personal and professional relationships through actionable, objective feedback. It focuses on a limited, significant network of individuals for each user, promoting continuous personal growth and relationship improvement."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"
dependencies:
  animated_visibility: ^0.0.4
  elegant_spring_animation: ^1.0.1
  flutter:
    sdk: flutter
  flutter_swipe_detector: ^2.0.0
  gap: ^3.0.1
  modal_bottom_sheet: ^3.0.0-pre
  sprung: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-ThinItalic.otf
          weight: 200
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-BlackItalic.otf
          weight: 900
          style: italic
